// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "apiKey": string;
      "port": number;
      "spaceId": string;
      "objectTypeKey": string;
      "syncMode": string;
      "initialized": boolean;
    };
  }
}
